name: Deploy to Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Версия Node.js, необходимая для сборки вашего шаблона

    - name: Install dependencies
      run: npm i --prefix local/templates/main

    - name: Build project
      run: npm run prod --prefix local/templates/main 

    - name: Copy local folder to temporary location
      run: cp -r local/templates/main /tmp/local_templates_main
      
    - name: Configure Git
      run: |
        git config --global user.name "kmakise668"
        git config --global user.email "kmakise668@gmail.com"

    - name: Add changes to Git index
      run: |
        git add .

    - name: Commit changes
      run: |
        git commit -m "Update local/templates/main folder"

    - name: Push changes to GitHub
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.DEVP_TOKEN }}

    - name: Deploy to Hosting
      run: |
        npm install -g ftp-deploy
        ftp-deploy --server 194.39.65.17 --user devpspa1 --password ~@KnCwYddcpro547 --local-dir . --remote-dir /httpdocs
