name: Bitrix Project CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2.5.0
        with:
          node-version: '16.x'

      - name: Install Composer
        run: |
          php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
          php composer-setup.php --filename=composer --install-dir=/usr/local/bin
          php -r "unlink('composer-setup.php');"

      - name: Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Copy Bitrix settings
        run: cp -R .settings.php.settings.php

      - name: Copy Bitrix configuration
        run: cp -R bitrix/.settings_extra.php.settings_extra.php

      - name: Set up Bitrix environment
        run: php -f bitrix/modules/main/tools/fix_kernel.php --ts=2015-07-01T00:00:00

      - name: Run Bitrix unit tests
        run: php -f bitrix/phpunit.php --verbose

      # Add any other necessary steps for your project here
