name: Bitrix CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'  # Версия PHP, используемая на вашем сервере Битрикс
        extensions: |
          bcmath
          mysqli
          curl
          
    - name: Install dependencies
      run: composer install --no-interaction --prefer-dist

    - name: Configure Bitrix environment
      run: cp bitrix/.settings.php.example bitrix/.settings.php

    - name: Configure Bitrix database
      run: cp bitrix/.settings_extra.php.example bitrix/.settings_extra.php

    - name: Build project
      run: |
        php -f bitrix/modules/main/tools/build_cache.php
        php -f update/update.php

    - name: Deploy project
      run: |
        rsync -avz --exclude 'bitrix/php_interface/dbconn.php' --exclude 'bitrix/managed_cache/' --exclude 'bitrix/cache/' --exclude 'upload/' ./ user@your-server:/path/to/destination/


    - name: Run tests
      run: |
        phpunit /path/to/tests/

    - name: Clear cache
      run: |
       rm -rf /path/to/bitrix/cache/
       rm -rf /path/to/bitrix/managed_cache/
